# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProAgeing' do
pod 'Alamofire'
pod 'SwiftyJSON'



end
  # Comment the next line if you're not using Swift and don't want to use dynamic 

use_frameworks!

target 'ProAgeingTests' do

   

end
target 'ProAgeingUITests' do

 

end
